name: Enrico Campidoglio
description: The blog of Enrico Campidoglio
markdown: kramdown
highlighter: rouge
url: http://megakemp.com
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: blog/page:num

gems:
  - jekyll-redirect-from

theme:
  # Base color for background elements such as the top bar
  base_color: '#444'
  # Accent color for links, etc
  highlight_color: '#e87830'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: ecampidoglio
    stackoverflow: 26396
    twitter: ecampidoglio
    rss: http://feeds.feedburner.com/thoughtology
    #bitbucket:
    #hacker_news:
    #stackexchange:
    #facebook:
    #tumblr:
    #linkedin:
    #gplus:

  # "Hi, I'm _______"
  name: Enrico Campidoglio
  email: enrico@tretton37.com
  tagline: ""

  # Google Analytics Tracking ID, leave blank to ignore
  google_analytics_tracking_id: UA-5422661-2
  google_analytics_property_name: megakemp.com

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
